# Generated by Django 4.2.3 on 2023-08-26 10:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "rate_limits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.hstore.HStoreField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="rate_limits",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="symbol")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "base_asset",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="baseAsset",
                    ),
                ),
                (
                    "base_asset_precision",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="baseAssetPrecision"
                    ),
                ),
                (
                    "quoteAsset",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="quoteAsset",
                    ),
                ),
                (
                    "quote_precision",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="quotePrecision"
                    ),
                ),
                (
                    "quote_asset_precision",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="quoteAssetPrecision"
                    ),
                ),
                (
                    "base_commission_precision",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="baseCommissionPrecision"
                    ),
                ),
                (
                    "quote_commission_precision",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="quoteCommissionPrecision"
                    ),
                ),
                (
                    "order_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="orderTypes",
                    ),
                ),
                (
                    "iceberg_allowed",
                    models.BooleanField(default=False, verbose_name="icebergAllowed"),
                ),
                (
                    "oco_allowed",
                    models.BooleanField(default=False, verbose_name="ocoAllowed"),
                ),
                (
                    "quote_order_qty_market_allowed",
                    models.BooleanField(
                        default=False, verbose_name="quoteOrderQtyMarketAllowed"
                    ),
                ),
                (
                    "allow_trailing_stop",
                    models.BooleanField(
                        default=False, verbose_name="allowTrailingStop"
                    ),
                ),
                (
                    "cancel_replace_allowed",
                    models.BooleanField(
                        default=False, verbose_name="cancelReplaceAllowed"
                    ),
                ),
                (
                    "is_spot_trading_allowed",
                    models.BooleanField(
                        default=False, verbose_name="isSpotTradingAllowed"
                    ),
                ),
                (
                    "is_margin_trading_allowed",
                    models.BooleanField(
                        default=False, verbose_name="isMarginTradingAllowed"
                    ),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="permissions",
                    ),
                ),
                (
                    "default_self_trade_prevention_mode",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="defaultSelfTradePreventionMode",
                    ),
                ),
                (
                    "allowed_self_trade_prevention_modes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="allowedSelfTradePreventionModes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Information",
                "verbose_name_plural": "Exchange Information",
            },
        ),
    ]
