# Generated by Django 4.2.3 on 2024-08-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("open_time", models.DateTimeField(verbose_name="openTime")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="openPrice"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="highPrice"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="lowPrice"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="closePrice"
                    ),
                ),
                ("volume", models.PositiveIntegerField(verbose_name="volume")),
                ("close_time", models.DateTimeField(verbose_name="closeTime")),
                (
                    "quote_asset_volume",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="quoteAssetVolume",
                    ),
                ),
                (
                    "number_of_trades",
                    models.PositiveIntegerField(verbose_name="numberOfTrades"),
                ),
                (
                    "taker_buy_base_asset_volume",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="takerBuyBaseAssetVolume",
                    ),
                ),
                (
                    "taker_buy_quote_asset_volume",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="takerBuyQuoteAssetVolume",
                    ),
                ),
                (
                    "unused_field_ignore",
                    models.BooleanField(verbose_name="unusedFieldIgnore"),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="klines",
                        to="market_data.exchangeinfo",
                        verbose_name="symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kline",
                "verbose_name_plural": "Kline",
            },
        ),
    ]
