# Generated by Django 4.2.3 on 2025-02-07 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kline",
            unique_together={("open_time", "symbol"), ("symbol", "open_time")},
        ),
    ]
