# Generated by Django 4.2.3 on 2024-08-18 22:14

from django.db import migrations

DATA = [
    ('MINUTE_1', '1m', 1),
    ('MINUTE_3', '3m', 3),
    ('MINUTE_5', '5m', 5),
    ('MINUTE_15', '15m', 15),
    ('MINUTE_30', '30m', 30),
    ('HOUR_1', '1h', 60),
    ('HOUR_2', '2h', 120),
    ('HOUR_4', '4h', 240),
    ('HOUR_6', '6h', 360),
    ('HOUR_8', '8h', 480),
    ('HOUR_12', '12h', 720),
    ('DAY_1', '1d', 1440),
    ('DAY_3', '3d', 4320),
    ('WEEK_1', '1w', 10080),
    ('MONTH_1', '1M', 43200),  # 30d
    ('YEAR_1', '1Y', 525600),
]


def code(apps, *_):
    Interval = apps.get_model('market_data', 'Interval')
    for codename, value, minutes_count in DATA:
        Interval.objects.get_or_create(
            codename=codename,
            value=value,
            minutes_count=minutes_count,
        )


def reverse_code(apps, *_):
    Interval = apps.get_model('market_data', 'Interval')
    Interval.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code, reverse_code, atomic=True)
    ]
