# Generated by Django 4.2.3 on 2024-09-04 20:38

from django.db import migrations

DATA = [
    ('YEAR_1', '1Y', 525600),
]


def code(apps, *_):
    Interval = apps.get_model('market_data', 'Interval')
    for codename, value, minutes_count in DATA:
        Interval.objects.get_or_create(
            codename=codename,
            value=value,
            minutes_count=minutes_count,
        )


def reverse_code(apps, *_):
    Interval = apps.get_model('market_data', 'Interval')
    Interval.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0002_auto_20240819_0114"),
    ]

    operations = [
        migrations.RunPython(code=code, reverse_code=reverse_code, atomic=True),
    ]
