# Generated by Django 4.2.3 on 2024-08-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0002_kline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "codename",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="codename"
                    ),
                ),
                (
                    "value",
                    models.CharField(default="", max_length=4, verbose_name="value"),
                ),
            ],
        ),
    ]
