# Generated by Django 4.2.3 on 2025-02-07 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0002_alter_kline_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kline",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="kline",
            index_together={("open_time", "symbol"), ("symbol", "open_time")},
        ),
    ]
