# Generated by Django 4.2.3 on 2025-02-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0003_alter_kline_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kline",
            name="open_time",
            field=models.DateTimeField(db_index=True, verbose_name="openTime"),
        ),
    ]
