# Generated by Django 4.2.3 on 2024-09-10 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0002_alter_movingaverage_interval"),
        ("market_data", "0003_alter_interval_options_alter_kline_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Interval",
        ),
    ]
