# Generated by Django 4.2.3 on 2024-08-23 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0003_auto_20240819_0114"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kline",
            unique_together={("symbol", "open_time")},
        ),
    ]
