# Generated by Django 4.2.3 on 2024-08-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0003_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interval",
            name="codename",
            field=models.CharField(
                max_length=15,
                primary_key=True,
                serialize=False,
                verbose_name="codename",
            ),
        ),
        migrations.AlterField(
            model_name="interval",
            name="value",
            field=models.CharField(max_length=4, verbose_name="value"),
        ),
    ]
