# Generated by Django 4.2.3 on 2024-08-18 22:14

from django.db import migrations

DATA = [
    ('MINUTE_1', '1m'),
    ('MINUTE_3', '3m'),
    ('MINUTE_5', '5m'),
    ('MINUTE_15', '15m'),
    ('MINUTE_30', '30m'),
    ('HOUR_1', '1h'),
    ('HOUR_2', '2h'),
    ('HOUR_4', '4h'),
    ('HOUR_6', '6h'),
    ('HOUR_8', '8h'),
    ('HOUR_12', '12h'),
    ('DAY_1', '1d'),
    ('DAY_3', '3d'),
    ('WEEK_1', '1w'),
    ('MONTH_1', '1M'),
]


def code(apps, *_):
    Interval = apps.get_model('market_data', 'Interval')
    for codename, value in DATA:
        Interval.objects.get_or_create(
            codename=codename,
            value=value,
        )


def reverse_code(apps, *_):
    Interval = apps.get_model('market_data', 'Interval')
    Interval.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0004_alter_interval_codename_alter_interval_value"),
    ]

    operations = [
        migrations.RunPython(code, reverse_code, atomic=True)
    ]
