# Generated by Django 4.2.3 on 2025-04-17 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0004_alter_kline_open_time"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="kline",
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="kline",
            unique_together={("symbol", "open_time"), ("open_time", "symbol")},
        ),
    ]
