# Generated by Django 4.2.3 on 2024-08-18 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0005_auto_20240819_0114"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interval",
            options={"verbose_name": "Interval", "verbose_name_plural": "Interval"},
        ),
    ]
