# Generated by Django 4.2.3 on 2024-08-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0006_alter_interval_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kline",
            name="volume",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="volume"
            ),
        ),
    ]
