# Generated by Django 4.2.3 on 2023-09-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepthOfMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Status"),
                ),
                (
                    "depth",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Depth"),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.exchangeinfo",
                        verbose_name="Symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Глубина рынка",
                "verbose_name_plural": "Глубина рынка",
            },
        ),
        migrations.CreateModel(
            name="TaskManagement",
            fields=[
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        verbose_name="codename",
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(default=False, verbose_name="is_working"),
                ),
            ],
            options={
                "verbose_name": "Task management",
                "verbose_name_plural": "Tasks management",
            },
        ),
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Status"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="Amount"),
                ),
                (
                    "depth",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Depth"),
                ),
                (
                    "depth_of_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streams.depthofmarket",
                        verbose_name="Depth of market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тестовые данные",
                "verbose_name_plural": "Тестовые данные",
            },
        ),
    ]
