# Generated by Django 4.2.3 on 2023-09-10 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0001_initial"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="trainingdata",
            index_together={("depth_of_market", "depth")},
        ),
    ]
