# Generated by Django 4.2.3 on 2023-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonVar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=100, verbose_name="codename")),
                (
                    "value",
                    models.CharField(blank=True, max_length=100, verbose_name="value"),
                ),
            ],
            options={
                "verbose_name": "Базовая настройка",
                "verbose_name_plural": "Базовые настройки",
            },
        ),
    ]
