# Generated by Django 4.2.3 on 2023-09-10 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0002_alter_trainingdata_index_together"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="trainingdata",
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="trainingdata",
            unique_together={("depth_of_market", "depth")},
        ),
    ]
