# Generated by Django 4.2.3 on 2023-09-02 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0002_commonvar"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskManagement",
            fields=[
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="codename"
                    ),
                ),
                ("is_work", models.BooleanField(default=True, verbose_name="is_work")),
            ],
            options={
                "verbose_name": "Управление задачей",
                "verbose_name_plural": "Управление задачами",
            },
        ),
        migrations.DeleteModel(
            name="CommonVar",
        ),
        migrations.DeleteModel(
            name="StreamTest",
        ),
    ]
