# Generated by Django 4.2.3 on 2023-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0003_taskmanagement_delete_commonvar_delete_streamtest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmanagement",
            name="id",
        ),
        migrations.AlterField(
            model_name="taskmanagement",
            name="codename",
            field=models.CharField(
                max_length=150,
                primary_key=True,
                serialize=False,
                verbose_name="codename",
            ),
        ),
    ]
