# Generated by Django 4.2.3 on 2023-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0004_remove_taskmanagement_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmanagement",
            name="is_work",
        ),
        migrations.AddField(
            model_name="taskmanagement",
            name="is_working",
            field=models.BooleanField(default=False, verbose_name="is_working"),
        ),
    ]
