# Generated by Django 4.2.3 on 2023-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0005_remove_taskmanagement_is_work_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepthOfMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("symbol", models.CharField(max_length=150, verbose_name="Symbol")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Status"),
                ),
            ],
            options={
                "verbose_name": "Глубина рынка",
                "verbose_name_plural": "Глубина рынка",
            },
        ),
    ]
