# Generated by Django 4.2.3 on 2023-09-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
        ("streams", "0006_depthofmarket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depthofmarket",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market_data.exchangeinfo",
                verbose_name="Symbol",
            ),
        ),
    ]
