# Generated by Django 4.2.3 on 2023-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0007_alter_depthofmarket_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="depthofmarket",
            name="depth",
            field=models.PositiveSmallIntegerField(default=100, verbose_name="Depth"),
        ),
    ]
