# Generated by Django 4.2.3 on 2023-09-10 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streams", "0009_trainingdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskmanagement",
            options={
                "verbose_name": "Task management",
                "verbose_name_plural": "Tasks management",
            },
        ),
    ]
