# Generated by Django 4.2.3 on 2024-09-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market_data", "0002_auto_20240819_0114"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovingAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("sma", "SMA"), ("ema", "EMA")],
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "kline_count",
                    models.IntegerField(
                        help_text="Количество свечей для расчета",
                        verbose_name="K-Line Count",
                    ),
                ),
                (
                    "factor_alfa",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Используется для расчета EMA",
                        max_digits=5,
                        verbose_name="Factor Alfa",
                    ),
                ),
                (
                    "factor_alfa_auto",
                    models.BooleanField(
                        default=False,
                        help_text="Используется для расчета EMA",
                        verbose_name="Factor Alfa Auto",
                    ),
                ),
                (
                    "interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.interval",
                        verbose_name="Interval",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.exchangeinfo",
                        verbose_name="Symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "MovingAverage",
                "verbose_name_plural": "MovingAverage",
            },
        ),
    ]
