# Generated by Django 4.2.3 on 2024-05-12 20:21

from django.db import migrations

STRATEGY_CODENAME = 'default'

NAME = 'Количество свечей для расчета'
CODENAME = 'average_price_count_candles'
VALUE = 25
DESCRIPTION = ''


def code(apps, *_):
    Strategy = apps.get_model('strategies.Strategy')
    strategy = Strategy.objects.get(
        codename=STRATEGY_CODENAME,
    )

    AveragePrice = apps.get_model('indicators.AveragePrice')
    AveragePrice.objects.create(
        strategy=strategy,
        name=NAME,
        codename=CODENAME,
        value=VALUE,
        description=DESCRIPTION,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code, atomic=True),
    ]
