# Generated by Django 4.2.3 on 2024-10-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
        ("strategies", "0002_strategyresult"),
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movingaverage",
            options={
                "verbose_name": "Moving Average",
                "verbose_name_plural": "Moving Averages",
            },
        ),
        migrations.CreateModel(
            name="StandardDeviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Codename"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("open", "Open price"),
                            ("close", "Close price"),
                            ("high", "High price"),
                            ("low", "Low price"),
                            ("high_low", "High-Low average"),
                            ("open_close", "Open-Close average"),
                        ],
                        max_length=20,
                        verbose_name="Data source",
                    ),
                ),
                (
                    "kline_count",
                    models.IntegerField(
                        help_text="Количество свечей для расчета",
                        verbose_name="K-Line Count",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1m", "Minute 1"),
                            ("1h", "Hour 1"),
                            ("1d", "Day 1"),
                            ("1w", "Week 1"),
                            ("1M", "Month 1"),
                            ("1Y", "Year 1"),
                        ],
                        max_length=10,
                        verbose_name="Interval",
                    ),
                ),
                (
                    "moving_average",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="indicators.movingaverage",
                        verbose_name="Moving Average",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="strategies.strategy",
                        verbose_name="Strategy",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.exchangeinfo",
                        verbose_name="Symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Deviation",
                "verbose_name_plural": "Standard Deviations",
            },
        ),
    ]
