# Generated by Django 4.2.3 on 2024-09-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movingaverage",
            name="interval",
            field=models.CharField(
                choices=[
                    ("1m", "MINUTE_1"),
                    ("3m", "MINUTE_3"),
                    ("5m", "MINUTE_5"),
                    ("15m", "MINUTE_15"),
                    ("30m", "MINUTE_30"),
                    ("1h", "HOUR_1"),
                    ("2h", "HOUR_2"),
                    ("4h", "HOUR_4"),
                    ("6h", "HOUR_6"),
                    ("8h", "HOUR_8"),
                    ("12h", "HOUR_12"),
                    ("1d", "DAY_1"),
                    ("3d", "DAY_3"),
                    ("1w", "WEEK_1"),
                    ("1M", "MONTH_1"),
                    ("1Y", "YEAR_1"),
                ],
                verbose_name="Interval",
            ),
        ),
    ]
