# Generated by Django 4.2.3 on 2024-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movingaverage",
            name="interval",
            field=models.CharField(
                choices=[
                    ("1m", "MINUTE_1"),
                    ("1h", "HOUR_1"),
                    ("1d", "DAY_1"),
                    ("1w", "WEEK_1"),
                    ("1M", "MONTH_1"),
                    ("1Y", "YEAR_1"),
                ],
                verbose_name="Interval",
            ),
        ),
    ]
