# Generated by Django 4.2.3 on 2024-10-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("strategies", "0001_initial"),
        ("indicators", "0001_initial"),
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movingaverage",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="strategies.strategy",
                verbose_name="Strategy",
            ),
        ),
        migrations.AddField(
            model_name="movingaverage",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market_data.exchangeinfo",
                verbose_name="Symbol",
            ),
        ),
        migrations.AddField(
            model_name="bollingerbands",
            name="moving_average",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.movingaverage",
                verbose_name="Moving Average",
            ),
        ),
        migrations.AddField(
            model_name="bollingerbands",
            name="standard_deviation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.standarddeviation",
                verbose_name="Standard Deviation",
            ),
        ),
    ]
