# Generated by Django 4.2.3 on 2024-09-14 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0002_alter_movingaverage_data_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movingaverage",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="movingaverage",
            name="symbol",
        ),
    ]
