# Generated by Django 4.2.3 on 2024-10-07 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0002_alter_movingaverage_options_standarddeviation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standarddeviation",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="standarddeviation",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="standarddeviation",
            name="symbol",
        ),
    ]
