# Generated by Django 4.2.3 on 2024-10-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0001_initial"),
        ("indicators", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standarddeviation",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="strategies.strategy",
                verbose_name="Strategy",
            ),
        ),
    ]
