# Generated by Django 4.2.3 on 2024-10-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0003_remove_standarddeviation_interval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BollingerBands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Codename"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "sigma_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=2,
                        max_digits=5,
                        verbose_name="Sigma Factor",
                    ),
                ),
                (
                    "moving_average",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="indicators.movingaverage",
                        verbose_name="Moving Average",
                    ),
                ),
                (
                    "standard_deviation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="indicators.standarddeviation",
                        verbose_name="Standard Deviation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bollinger Bands",
                "verbose_name_plural": "Bollinger Bands",
            },
        ),
    ]
