# Generated by Django 4.2.3 on 2024-05-18 12:24

from django.db import migrations

STRATEGY_CODENAME = 'default'

NAME = 'Количество свечей для расчета'
CODENAME = 'moving average_count_candle'
VALUE = '25'
DESCRIPTION = ''


def code(apps, *_):
    Strategy = apps.get_model('strategies.Strategy')
    strategy = Strategy.objects.get(
        codename=STRATEGY_CODENAME,
    )

    MovingAverage = apps.get_model('indicators.MovingAverage')
    MovingAverage.objects.create(
        strategy=strategy,
        name=NAME,
        codename=CODENAME,
        value=VALUE,
        description=DESCRIPTION,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0003_auto_20240513_0122"),
    ]

    operations = [
        migrations.RunPython(code, atomic=True),
    ]
