# Generated by Django 4.2.3 on 2024-09-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0002_remove_strategy_moving_average_and_more"),
        ("indicators", "0003_remove_movingaverage_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movingaverage",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="strategies.strategy",
                verbose_name="Strategy",
            ),
        ),
    ]
