# Generated by Django 4.2.3 on 2024-09-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
        ("indicators", "0004_movingaverage_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="movingaverage",
            name="interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1m", "Minute 1"),
                    ("1h", "Hour 1"),
                    ("1d", "Day 1"),
                    ("1w", "Week 1"),
                    ("1M", "Month 1"),
                    ("1Y", "Year 1"),
                ],
                max_length=10,
                null=True,
                verbose_name="Interval",
            ),
        ),
        migrations.AddField(
            model_name="movingaverage",
            name="symbol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market_data.exchangeinfo",
                verbose_name="Symbol",
            ),
        ),
    ]
