# Generated by Django 4.2.3 on 2024-12-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0004_alter_movingaverage_data_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarddeviation",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("open", "Open price"),
                    ("close", "Close price"),
                    ("high", "High price"),
                    ("low", "Low price"),
                    ("high_low", "High-Low average"),
                    ("open_close", "Open-Close average"),
                    ("cross_course", "Cross course"),
                ],
                max_length=20,
                verbose_name="Data source",
            ),
        ),
    ]
