# Generated by Django 4.2.3 on 2025-01-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0019_remove_arbitration_moving_average_and_more"),
        ("indicators", "0005_alter_standarddeviation_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="movingaverage",
            name="arbitration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="arbitrations.arbitration",
                verbose_name="Arbitration",
            ),
        ),
        migrations.AddField(
            model_name="standarddeviation",
            name="arbitration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="arbitrations.arbitration",
                verbose_name="Arbitration",
            ),
        ),
    ]
