# Generated by Django 4.2.3 on 2024-09-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0007_remove_movingaverage_make_self_df_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movingaverage",
            name="is_use_own_df",
            field=models.BooleanField(default=False, verbose_name="Use own DF"),
        ),
    ]
