# Generated by Django 4.2.3 on 2025-02-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0024_alter_arbitration_interval"),
        ("indicators", "0008_standarddeviation_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movingaverage",
            name="interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1min", "Minute 1"),
                    ("1h", "Hour 1"),
                    ("2h", "Hour 2"),
                    ("4h", "Hour 4"),
                    ("6h", "Hour 6"),
                    ("8h", "Hour 8"),
                    ("12h", "Hour 12"),
                    ("1D", "Day 1"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                max_length=10,
                null=True,
                verbose_name="Interval",
            ),
        ),
        migrations.AlterField(
            model_name="standarddeviation",
            name="interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1min", "Minute 1"),
                    ("1h", "Hour 1"),
                    ("2h", "Hour 2"),
                    ("4h", "Hour 4"),
                    ("6h", "Hour 6"),
                    ("8h", "Hour 8"),
                    ("12h", "Hour 12"),
                    ("1D", "Day 1"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                max_length=10,
                null=True,
                verbose_name="Interval",
            ),
        ),
        migrations.CreateModel(
            name="BetaFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Codename"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "kline_count",
                    models.IntegerField(
                        help_text="Количество свечей для расчета",
                        verbose_name="K-Line Count",
                    ),
                ),
                (
                    "variance_price_comparison",
                    models.CharField(
                        choices=[
                            ("open_price", "Open price"),
                            ("close_price", "Close price"),
                            ("high_price", "High price"),
                            ("low_price", "Low price"),
                        ],
                        default="close_price",
                        verbose_name="Variance price comparison ",
                    ),
                ),
                (
                    "covariance_price_comparison",
                    models.CharField(
                        choices=[
                            ("open_price", "Open price"),
                            ("close_price", "Close price"),
                            ("high_price", "High price"),
                            ("low_price", "Low price"),
                        ],
                        default="close_price",
                        verbose_name="Covariance price comparison ",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1min", "Minute 1"),
                            ("1h", "Hour 1"),
                            ("2h", "Hour 2"),
                            ("4h", "Hour 4"),
                            ("6h", "Hour 6"),
                            ("8h", "Hour 8"),
                            ("12h", "Hour 12"),
                            ("1D", "Day 1"),
                            ("1W", "Week 1"),
                            ("1M", "Month 1"),
                            ("1A", "Year 1"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Interval",
                    ),
                ),
                (
                    "arbitration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="arbitrations.arbitration",
                        verbose_name="Arbitration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beta Factor",
                "verbose_name_plural": "Beta Factor",
            },
        ),
    ]
