# Generated by Django 4.2.3 on 2025-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0009_alter_movingaverage_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="betafactor",
            name="market_symbol",
            field=models.CharField(
                choices=[("symbol_1", "Symbol 1"), ("symbol_2", "Symbol 2")],
                default="symbol_1",
                help_text="Symbol for variance",
                verbose_name="Market symbol",
            ),
        ),
        migrations.AddField(
            model_name="betafactor",
            name="price_comparison",
            field=models.CharField(
                choices=[
                    ("open_price", "Open price"),
                    ("close_price", "Close price"),
                    ("high_price", "High price"),
                    ("low_price", "Low price"),
                ],
                default="close_price",
                help_text="For Cross course",
                verbose_name="Price comparison",
            ),
        ),
    ]
