# Generated by Django 4.2.3 on 2025-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0010_betafactor_market_symbol_betafactor_price_comparison"),
    ]

    operations = [
        migrations.AddField(
            model_name="betafactor",
            name="type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ols", "OLS")],
                default="ols",
                verbose_name="Type",
            ),
        ),
    ]
