# Generated by Django 4.2.3 on 2025-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0011_betafactor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="betafactor",
            name="ema_span",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Период span для сглаживания",
                verbose_name="EMA span",
            ),
        ),
        migrations.AlterField(
            model_name="betafactor",
            name="type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ols", "OLS"), ("ema", "EMA")],
                default="ols",
                verbose_name="Type",
            ),
        ),
    ]
