# Generated by Django 4.2.3 on 2025-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0013_betafactor_butterworth_cutoff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betafactor",
            name="butterworth_order",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="✔ Для короткосрочного анализа (1-10 дней) → cutoff=0.1, order=3 ✔ Для среднесрочного анализа (10-50 дней) → cutoff=0.05, order=3-5 ✔ Для долгосрочного анализа (50+ дней) → cutoff=0.01, order=5-7",
                verbose_name="Butterworth order",
            ),
        ),
    ]
