# Generated by Django 4.2.3 on 2025-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0015_alter_movingaverage_data_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarddeviation",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("open", "Open price"),
                    ("close", "Close price"),
                    ("high", "High price"),
                    ("low", "Low price"),
                    ("high_low", "High-Low average"),
                    ("open_close", "Open-Close average"),
                    ("cross_course", "Cross course"),
                    ("beta_spread", "Beta spread"),
                ],
                max_length=20,
                verbose_name="Data source",
            ),
        ),
    ]
