# Generated by Django 4.2.3 on 2025-02-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0016_alter_standarddeviation_data_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movingaverage",
            name="kline_count",
        ),
        migrations.AddField(
            model_name="movingaverage",
            name="windows_size",
            field=models.IntegerField(
                default=21,
                help_text="Количество свечей для расчета",
                verbose_name="Windows size",
            ),
        ),
    ]
