# Generated by Django 4.2.3 on 2025-02-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0017_remove_movingaverage_kline_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betafactor",
            name="kline_count",
        ),
        migrations.RemoveField(
            model_name="standarddeviation",
            name="kline_count",
        ),
        migrations.AddField(
            model_name="betafactor",
            name="windows_size",
            field=models.IntegerField(
                default=21,
                help_text="Количество свечей для расчета",
                verbose_name="Windows size",
            ),
        ),
        migrations.AddField(
            model_name="standarddeviation",
            name="windows_size",
            field=models.IntegerField(
                default=21,
                help_text="Количество свечей для расчета",
                verbose_name="Windows size",
            ),
        ),
    ]
