# Generated by Django 4.2.3 on 2025-02-21 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0018_remove_betafactor_kline_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="betafactor",
            old_name="windows_size",
            new_name="window_size",
        ),
        migrations.RenameField(
            model_name="movingaverage",
            old_name="windows_size",
            new_name="window_size",
        ),
        migrations.RenameField(
            model_name="standarddeviation",
            old_name="windows_size",
            new_name="window_size",
        ),
    ]
