# Generated by Django 4.2.3 on 2025-02-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0019_rename_windows_size_betafactor_window_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betafactor",
            name="window_size",
            field=models.IntegerField(
                default=21,
                help_text="Количество свечей для расчета",
                verbose_name="Window size",
            ),
        ),
        migrations.AlterField(
            model_name="movingaverage",
            name="window_size",
            field=models.IntegerField(
                default=21,
                help_text="Количество свечей для расчета",
                verbose_name="Window size",
            ),
        ),
        migrations.AlterField(
            model_name="standarddeviation",
            name="window_size",
            field=models.IntegerField(
                default=21,
                help_text="Количество свечей для расчета",
                verbose_name="Window size",
            ),
        ),
    ]
