# Generated by Django 4.2.3 on 2025-02-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0020_alter_betafactor_window_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betafactor",
            name="type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("ols", "OLS"),
                    ("ols_ema", "OLS-EMA"),
                    ("bw", "Butterworth"),
                ],
                default="ols",
                verbose_name="Type",
            ),
        ),
    ]
