version: '2.4'

services:
  django:
    container_name: ${COMPOSE_PROJECT_NAME}_django
    image: ${COMPOSE_PROJECT_NAME}_python
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
    networks:
      - bendernetwork
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres_db
      - redis
      - celery
      - flower
      - rabbitmq
      - celerybeat

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:7-alpine
    networks:
      - bendernetwork

  celery:
    container_name: ${COMPOSE_PROJECT_NAME}_celery
    depends_on:
      - postgres_db
      - redis
      - rabbitmq
    image: ${COMPOSE_PROJECT_NAME}_python
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - bendernetwork
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    command: celery -A bender.celery_entry worker -l info

  celerybeat:
    container_name: ${COMPOSE_PROJECT_NAME}_celerybeat
    depends_on:
      - celery
    image: ${COMPOSE_PROJECT_NAME}_python
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - bendernetwork
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    entrypoint: celery -A bender.celery_entry beat

  postgres_db:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    hostname: postgres
    image: postgres:14.1-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - "5435:5432"
    networks:
      - bendernetwork
    volumes:
      - benderdb:/var/lib/postgres_14/data
    environment:
      - POSTGRES_DB=bender
      - POSTGRES_USER=bender
      - POSTGRES_PASSWORD=bender
      - POSTGRES_PORT=5432

  rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    image: rabbitmq:3.9.11-management
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - "${RABBITMQ_PUBLIC_PORT:-15672}:15672"
    networks:
      - bendernetwork

  flower:
    container_name: ${COMPOSE_PROJECT_NAME}_flower
    depends_on:
      - celery
    image: ${COMPOSE_PROJECT_NAME}_python
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - bendernetwork
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    command: celery -A bender.celery_entry flower --port=5555

networks:
  bendernetwork:

volumes:
  benderdb:
