# Generated by Django 4.2.3 on 2023-08-25 22:46

""" САМАЯ ПЕРВАЯ МИГРАЦИЯ ПОСЛЕ СИСТЕМНЫХ.
Устанавливает расширение hstore в PostgreSQL.
Для поддержки HStoreField()
"""


from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [HStoreExtension()]
