# Generated by Django 4.2.3 on 2023-08-25 22:46

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [HStoreExtension()]
