# Generated by Django 4.2.3 on 2025-07-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniswapPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "pool_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNISWAP_V1", " Uniswap V1"),
                            ("UNISWAP_V2", " Uniswap V2"),
                            ("UNISWAP_V3", " Uniswap V3"),
                            ("UNISWAP_V4", " Uniswap V4"),
                        ],
                        null=True,
                        verbose_name="Pool Type",
                    ),
                ),
                (
                    "pool_address",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        null=True,
                        verbose_name="Pool Address",
                    ),
                ),
                (
                    "token_0",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        null=True,
                        verbose_name="Token 0 Address",
                    ),
                ),
                (
                    "token_1",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        null=True,
                        verbose_name="Token 1 Address",
                    ),
                ),
                (
                    "fee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fee"
                    ),
                ),
                (
                    "tick_spacing",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='tickSpacing — это ключевой параметр пула, который определяет шаг между доступными "тиками" цен (price ticks), на которых можно размещать ликвидность.',
                        null=True,
                        verbose_name="Tick Spacing",
                    ),
                ),
                (
                    "block_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Block Number"
                    ),
                ),
                (
                    "block_timestamp",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Block Timestamp"
                    ),
                ),
                ("removed", models.BooleanField(null=True, verbose_name="Removed")),
            ],
            options={
                "verbose_name": "Uniswap Pool",
                "verbose_name_plural": "Uniswap Pools",
            },
        ),
    ]
