# Generated by Django 4.2.3 on 2025-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MempoolTransaction",
            fields=[
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Transaction Hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mempool Transaction",
                "verbose_name_plural": "Mempool Transactions",
            },
        ),
    ]
