# Generated by Django 4.2.3 on 2025-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uniswappool",
            old_name="token_0",
            new_name="token_0_address",
        ),
        migrations.RenameField(
            model_name="uniswappool",
            old_name="token_1",
            new_name="token_1_address",
        ),
        migrations.AddField(
            model_name="uniswappool",
            name="block_hash",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Block Hash"
            ),
        ),
        migrations.AddField(
            model_name="uniswappool",
            name="log_index",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Log Index"
            ),
        ),
        migrations.AddField(
            model_name="uniswappool",
            name="transaction_hash",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Transaction Hash"
            ),
        ),
        migrations.AddField(
            model_name="uniswappool",
            name="transaction_index",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Transaction Index"
            ),
        ),
    ]
