# Generated by Django 4.2.3 on 2025-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0002_mempooltransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Transaction Hash",
                    ),
                ),
                (
                    "block_hash",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Block Hash"
                    ),
                ),
                (
                    "block_number",
                    models.PositiveBigIntegerField(
                        null=True, verbose_name="Block Number"
                    ),
                ),
                (
                    "from_address",
                    models.CharField(max_length=42, null=True, verbose_name="From"),
                ),
                (
                    "to_address",
                    models.CharField(max_length=42, null=True, verbose_name="To"),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(null=True, verbose_name="Value"),
                ),
                ("gas", models.PositiveBigIntegerField(null=True, verbose_name="Gas")),
                (
                    "input",
                    models.CharField(max_length=255, null=True, verbose_name="Input"),
                ),
                (
                    "nonce",
                    models.PositiveBigIntegerField(null=True, verbose_name="Nonce"),
                ),
                (
                    "tx_index",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Transaction Index"
                    ),
                ),
                (
                    "gas_price",
                    models.PositiveBigIntegerField(null=True, verbose_name="gasPrice"),
                ),
                (
                    "max_fee_per_gas",
                    models.PositiveBigIntegerField(
                        null=True, verbose_name="maxFeePerGas"
                    ),
                ),
                (
                    "max_priority_fee_per_gas",
                    models.PositiveBigIntegerField(
                        null=True, verbose_name="maxPriorityFeePerGas"
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(null=True, verbose_name="Type"),
                ),
                (
                    "chain_id",
                    models.PositiveBigIntegerField(null=True, verbose_name="ChainId"),
                ),
                (
                    "y_parity",
                    models.PositiveSmallIntegerField(null=True, verbose_name="yParity"),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.DeleteModel(
            name="MempoolTransaction",
        ),
    ]
