# Generated by Django 4.2.3 on 2025-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0003_transaction_delete_mempooltransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="access_list",
            field=models.TextField(null=True, verbose_name="Access List"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="input",
            field=models.TextField(null=True, verbose_name="Input"),
        ),
    ]
