# Generated by Django 4.2.3 on 2025-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0004_transaction_access_list_alter_transaction_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="gas",
            field=models.TextField(null=True, verbose_name="Gas"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_price",
            field=models.TextField(null=True, verbose_name="gasPrice"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_fee_per_gas",
            field=models.TextField(null=True, verbose_name="maxFeePerGas"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_priority_fee_per_gas",
            field=models.TextField(null=True, verbose_name="maxPriorityFeePerGas"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.TextField(null=True, verbose_name="Value"),
        ),
    ]
