# Generated by Django 4.2.3 on 2025-07-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0005_alter_transaction_gas_alter_transaction_gas_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Codename"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "pool_0",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_0",
                        to="defi.uniswappool",
                        verbose_name="Pool 0",
                    ),
                ),
                (
                    "pool_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_1",
                        to="defi.uniswappool",
                        verbose_name="Pool 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Swap Chain",
                "verbose_name_plural": "Swap Chains",
            },
        ),
    ]
