# Generated by Django 4.2.3 on 2025-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0006_swapchain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERC20Token",
            fields=[
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Address",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=50, null=True, verbose_name="Symbol"),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Decimals"
                    ),
                ),
                (
                    "total_supply",
                    models.BigIntegerField(null=True, verbose_name="Total Supply"),
                ),
                (
                    "owner",
                    models.CharField(max_length=42, null=True, verbose_name="Owner"),
                ),
                (
                    "version",
                    models.CharField(max_length=50, null=True, verbose_name="Version"),
                ),
                (
                    "domain_separator",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Domain Separator"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERC-20 Token",
                "verbose_name_plural": "ERC-20 Tokens",
            },
        ),
    ]
