# Generated by Django 4.2.3 on 2025-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0007_erc20token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erc20token",
            name="total_supply",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Total Supply"
            ),
        ),
    ]
