# Generated by Django 4.2.3 on 2025-08-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0008_alter_erc20token_total_supply"),
    ]

    operations = [
        migrations.AddField(
            model_name="swapchain",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
    ]
