# Generated by Django 4.2.3 on 2025-08-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0009_swapchain_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoolLiquidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("reserve0", models.CharField(max_length=255, verbose_name="reserve0")),
                ("reserve1", models.CharField(max_length=255, verbose_name="reserve1")),
                (
                    "pool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="defi.uniswappool",
                        verbose_name="UniswapPool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pool Liquidity",
                "verbose_name_plural": "Pool Liquidies",
            },
        ),
    ]
