# Generated by Django 4.2.3 on 2026-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0010_poolliquidity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "tx_hash",
                    models.CharField(
                        max_length=66,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Transaction Hash",
                    ),
                ),
                ("chain_id", models.PositiveIntegerField(verbose_name="Chain ID")),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("swap", "Swap"),
                            ("mint", "Mint"),
                            ("burn", "Burn"),
                            ("collect", "Collect"),
                            ("approve", "Approve"),
                            ("decrease_liquidity", "Decrease Liquidity"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "ethereum_tx_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "legacy"), (1, "EIP-2930"), (2, "EIP-1559")],
                        verbose_name="Ethereum Transaction Type",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="Status")),
                (
                    "wallet_address",
                    models.CharField(max_length=42, verbose_name="Wallet Address"),
                ),
                ("nonce", models.PositiveBigIntegerField(verbose_name="Nonce")),
                (
                    "block_number",
                    models.PositiveBigIntegerField(verbose_name="Block Number"),
                ),
                ("gas_used", models.PositiveBigIntegerField(verbose_name="Gas Used")),
                (
                    "gas_used_for_l1",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Gas Used For L1"
                    ),
                ),
                (
                    "effective_gas_price",
                    models.PositiveBigIntegerField(verbose_name="Effective Gas Price"),
                ),
                (
                    "total_gas_cost_wei",
                    models.PositiveBigIntegerField(verbose_name="Total Gas Cost WEI"),
                ),
                (
                    "total_gas_cost_eth",
                    models.DecimalField(
                        decimal_places=18,
                        max_digits=30,
                        verbose_name="Total Gas Cost ETH",
                    ),
                ),
                (
                    "total_gas_cost_usdc",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        verbose_name="Total Gas Cost USDC",
                    ),
                ),
                (
                    "native_token_price_usdc",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Snapshot at moment.",
                        max_digits=20,
                        verbose_name="Native Token Price USDC",
                    ),
                ),
                ("gas_limit", models.PositiveBigIntegerField(verbose_name="Gas Limit")),
                (
                    "max_fee_per_gas",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Max Fee per Gas"
                    ),
                ),
                (
                    "max_priority_fee_per_gas",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Max Priority Fee per Gas"
                    ),
                ),
                (
                    "gas_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Only legacy transactions are supported.",
                        null=True,
                        verbose_name="Gas Price",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Created At")),
            ],
            options={
                "verbose_name": "Blockchain Transaction",
                "verbose_name_plural": "Blockchain Transaction",
            },
        ),
    ]
