# Generated by Django 4.2.3 on 2026-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0011_blockchaintransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="block_number",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Block Number"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="chain_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Chain ID"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="effective_gas_price",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Effective Gas Price"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="ethereum_tx_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "legacy"), (1, "EIP-2930"), (2, "EIP-1559")],
                null=True,
                verbose_name="Ethereum Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="gas_limit",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Gas Limit"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="gas_used",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Gas Used"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="native_token_price_usdc",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Snapshot at moment.",
                max_digits=20,
                null=True,
                verbose_name="Native Token Price USDC",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="nonce",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Nonce"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="status",
            field=models.BooleanField(blank=True, null=True, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="total_gas_cost_eth",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=30,
                null=True,
                verbose_name="Total Gas Cost ETH",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="total_gas_cost_usdc",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Total Gas Cost USDC",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="total_gas_cost_wei",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Total Gas Cost WEI"
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="tx_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("swap", "Swap"),
                    ("mint", "Mint"),
                    ("burn", "Burn"),
                    ("collect", "Collect"),
                    ("approve", "Approve"),
                    ("decrease_liquidity", "Decrease Liquidity"),
                ],
                max_length=20,
                null=True,
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="wallet_address",
            field=models.CharField(
                blank=True, max_length=42, null=True, verbose_name="Wallet Address"
            ),
        ),
    ]
