# Generated by Django 4.2.3 on 2026-05-25 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defi", "0012_alter_blockchaintransaction_block_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockchainTransaction",
        ),
    ]
