# Generated by Django 4.2.3 on 2023-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_pairs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingpair",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="tradingpair",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
    ]
