# Generated by Django 4.2.3 on 2023-07-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_pairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='is_favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
