# Generated by Django 4.2.3 on 2024-12-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arbitration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("codename", models.CharField(max_length=100, verbose_name="Codename")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1m", "Minute 1"),
                            ("1h", "Hour 1"),
                            ("1d", "Day 1"),
                            ("1w", "Week 1"),
                            ("1M", "Month 1"),
                            ("1Y", "Year 1"),
                        ],
                        default="1m",
                        max_length=10,
                        verbose_name="Base interval",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End time"
                    ),
                ),
                (
                    "symbol_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arbitration_set_first",
                        to="market_data.exchangeinfo",
                        verbose_name="Symbol 1",
                    ),
                ),
                (
                    "symbol_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arbitration_set_second",
                        to="market_data.exchangeinfo",
                        verbose_name="Symbol 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbitration",
                "verbose_name_plural": "Arbitrations",
            },
        ),
    ]
