# Generated by Django 4.2.3 on 2024-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="price_comparison",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open price"),
                    ("CLOSE", "Close price"),
                    ("HIGH", "High price"),
                    ("LOW", "Low price"),
                ],
                default="CLOSE",
                verbose_name="Price comparison",
            ),
        ),
    ]
