# Generated by Django 4.2.3 on 2024-12-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0003_standarddeviation_strategy"),
        ("arbitrations", "0002_arbitration_price_comparison"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="moving_average",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.movingaverage",
                verbose_name="Moving average",
            ),
        ),
        migrations.AlterField(
            model_name="arbitration",
            name="price_comparison",
            field=models.CharField(
                choices=[
                    ("open_price", "Open price"),
                    ("close_price", "Close price"),
                    ("high_price", "High price"),
                    ("low_price", "Low price"),
                ],
                default="close_price",
                verbose_name="Price comparison",
            ),
        ),
    ]
