# Generated by Django 4.2.3 on 2024-12-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0004_alter_movingaverage_data_source_and_more"),
        ("arbitrations", "0003_arbitration_moving_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="standard_deviation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.standarddeviation",
                verbose_name="Standard deviation",
            ),
        ),
    ]
