# Generated by Django 4.2.3 on 2024-12-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0005_alter_standarddeviation_data_source"),
        ("arbitrations", "0004_arbitration_standard_deviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="close_deal_sd",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Close deal SD",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="entry_price_order",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open price"),
                    ("CLOSE", "Close price"),
                    ("HIGH", "High price"),
                    ("LOW", "Low price"),
                    ("MAXMIN", "MaxMin"),
                    ("MINMAX", "MinMax"),
                ],
                default="MAXMIN",
                help_text="В каком порядке подавать цены свечи при тестировании стратегии",
                max_length=50,
                verbose_name="Entry price order",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="fixed_bet_amount",
            field=models.DecimalField(
                decimal_places=10,
                default=1.0,
                help_text="Сумма двух инструментов в сделке",
                max_digits=20,
                verbose_name="Fixed bet amount",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="maker_commission",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=4,
                verbose_name="Maker commission",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="open_deal_sd",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Open deal SD",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="taker_commission",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=4,
                verbose_name="Taker commission",
            ),
        ),
        migrations.AlterField(
            model_name="arbitration",
            name="moving_average",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.movingaverage",
                verbose_name="Moving average",
            ),
        ),
        migrations.AlterField(
            model_name="arbitration",
            name="standard_deviation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.standarddeviation",
                verbose_name="Standard deviation",
            ),
        ),
    ]
