# Generated by Django 4.2.3 on 2025-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0005_arbitration_close_deal_sd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="ratio_type",
            field=models.CharField(
                choices=[("price", "Price ratio")],
                default="price",
                help_text="По соотношению цены на входе в сделку",
                max_length=20,
                verbose_name="Ratio type",
            ),
        ),
    ]
