# Generated by Django 4.2.3 on 2025-01-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0009_arbitrationdeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitrationdeal",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Quantity",
            ),
        ),
    ]
