# Generated by Django 4.2.3 on 2025-01-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0010_arbitrationdeal_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitrationdeal",
            name="quantity",
            field=models.DecimalField(
                decimal_places=10, default=0, max_digits=20, verbose_name="Quantity"
            ),
        ),
    ]
