# Generated by Django 4.2.3 on 2025-01-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0013_alter_arbitration_ratio_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="b_factor_price_comparison",
            field=models.CharField(
                choices=[
                    ("open_price", "Open price"),
                    ("close_price", "Close price"),
                    ("high_price", "High price"),
                    ("low_price", "Low price"),
                ],
                default="close_price",
                verbose_name="B-factor price comparison",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="b_factor_window",
            field=models.PositiveIntegerField(
                default=1, verbose_name="B-factor size of window"
            ),
        ),
    ]
