# Generated by Django 4.2.3 on 2025-01-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0014_arbitration_b_factor_price_comparison_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitrationdeal",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("close", "Close"),
                    ("profit", "Profit"),
                    ("loss", "Loss"),
                    ("unknown", "Unknown"),
                    ("correction", "Correction"),
                ],
                verbose_name="State",
            ),
        ),
    ]
