# Generated by Django 4.2.3 on 2025-01-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0015_alter_arbitrationdeal_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitrationdeal",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="+ short position, - long position",
                max_digits=20,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
