# Generated by Django 4.2.3 on 2025-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0016_arbitrationdeal_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitrationdeal",
            name="beta_quantity_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Beta quantity 1",
            ),
        ),
        migrations.AddField(
            model_name="arbitrationdeal",
            name="beta_quantity_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Beta quantity 2",
            ),
        ),
    ]
