# Generated by Django 4.2.3 on 2025-01-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0017_arbitrationdeal_beta_quantity_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="correction_type",
            field=models.CharField(
                choices=[("none", "None"), ("every_time", "Every time")],
                default="none",
                verbose_name="Correction type",
            ),
        ),
    ]
