# Generated by Django 4.2.3 on 2025-01-29 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0018_arbitration_correction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arbitration",
            name="moving_average",
        ),
        migrations.RemoveField(
            model_name="arbitration",
            name="standard_deviation",
        ),
    ]
