# Generated by Django 4.2.3 on 2025-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0020_remove_arbitration_price_comparison_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="price_comparison",
            field=models.CharField(
                choices=[
                    ("open_price", "Open price"),
                    ("close_price", "Close price"),
                    ("high_price", "High price"),
                    ("low_price", "Low price"),
                ],
                default="close_price",
                help_text="Влияет только на отображение результатов в чарте. Обычно должен совпадать с настройкой в MA.",
                verbose_name="Price comparison",
            ),
        ),
    ]
