# Generated by Django 4.2.3 on 2025-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0021_arbitration_price_comparison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitration",
            name="interval",
            field=models.CharField(
                choices=[
                    ("1T", "Minute 1"),
                    ("1H", "Hour 1"),
                    ("1D", "Day 1"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                default="1T",
                help_text="Влияет только на отображение результатов в чарте.",
                max_length=10,
                verbose_name="Base interval",
            ),
        ),
    ]
