# Generated by Django 4.2.3 on 2025-02-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0024_alter_arbitration_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arbitration",
            name="b_factor_price_comparison",
        ),
        migrations.RemoveField(
            model_name="arbitration",
            name="b_factor_window",
        ),
        migrations.AddIndex(
            model_name="arbitrationdeal",
            index=models.Index(
                fields=["arbitration", "symbol", "state", "deal_time"],
                name="arbitration_arbitra_f20b7e_idx",
            ),
        ),
    ]
