# Generated by Django 4.2.3 on 2025-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0026_alter_arbitration_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitration",
            name="price_comparison",
            field=models.CharField(
                choices=[
                    ("open_price", "Open price"),
                    ("close_price", "Close price"),
                    ("high_price", "High price"),
                    ("low_price", "Low price"),
                ],
                default="close_price",
                help_text="Задает базовое сравнение цены для cross course.",
                verbose_name="Price comparison",
            ),
        ),
    ]
