# Generated by Django 4.2.3 on 2025-02-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0027_alter_arbitration_price_comparison"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="z_index",
            field=models.CharField(
                choices=[
                    ("cross_course", "Cross course"),
                    ("beta_spread", "Beta spread"),
                ],
                default="cross_course",
                help_text="Выбор способа определения спреда для арбитража",
                verbose_name="Z-Index",
            ),
        ),
        migrations.AlterField(
            model_name="arbitration",
            name="price_comparison",
            field=models.CharField(
                choices=[
                    ("open_price", "Open price"),
                    ("close_price", "Close price"),
                    ("high_price", "High price"),
                    ("low_price", "Low price"),
                ],
                default="close_price",
                help_text="Задает базовую цену для расчета индикаторов и cross course.",
                verbose_name="Price comparison",
            ),
        ),
    ]
