# Generated by Django 4.2.3 on 2025-02-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0028_arbitration_z_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="correlation_window",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Аналитический параметр. Окно для расчета корреляции.",
                verbose_name="Correlation window",
            ),
        ),
    ]
