# Generated by Django 4.2.3 on 2025-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0033_alter_arbitration_price_comparison"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitrationdeal",
            name="deal_uid",
            field=models.UUIDField(null=True, verbose_name="Deal UID"),
        ),
    ]
