# Generated by Django 4.2.3 on 2025-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0034_arbitrationdeal_deal_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("cross_course", "Cross course"),
                    ("beta", "Beta"),
                    ("beta_spread", "Beta spread"),
                    ("beta_spread_log", "Beta spread log"),
                ],
                default="cross_course",
                help_text="Выбор данных для работы стратегии",
                max_length=20,
                verbose_name="Data source",
            ),
        ),
    ]
