# Generated by Django 4.2.3 on 2025-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0036_alter_arbitration_data_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arbitration",
            name="correlation_window",
        ),
        migrations.AddField(
            model_name="arbitration",
            name="corr_window",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Окно для расчета корреляции.",
                verbose_name="Corr window",
            ),
        ),
    ]
