# Generated by Django 4.2.3 on 2025-03-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0037_remove_arbitration_correlation_window_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitration",
            name="corr_open_deal_type",
            field=models.CharField(
                choices=[("not_used", "Not used"), ("pearson", "Pearson")],
                default="not_used",
                verbose_name="Corr open deal type",
            ),
        ),
        migrations.AddField(
            model_name="arbitration",
            name="corr_open_deal_value",
            field=models.FloatField(
                default=0.85,
                help_text="Значение корреляции для открытия сделки, не менее.",
                verbose_name="Corr open deal",
            ),
        ),
    ]
