# Generated by Django 4.2.3 on 2025-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0038_arbitration_corr_open_deal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitration",
            name="corr_open_deal_value",
            field=models.FloatField(
                default=0.85,
                help_text="Значение корреляции для открытия сделки, не менее.",
                verbose_name="Corr open deal value",
            ),
        ),
    ]
