# Generated by Django 4.2.3 on 2025-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0039_alter_arbitration_corr_open_deal_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arbitration",
            name="corr_open_deal_type",
        ),
        migrations.AddField(
            model_name="arbitration",
            name="corr_type",
            field=models.CharField(
                choices=[("not_used", "Not used"), ("pearson", "Pearson")],
                default="not_used",
                verbose_name="Corr type",
            ),
        ),
    ]
