# Generated by Django 4.2.3 on 2025-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0040_remove_arbitration_corr_open_deal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitration",
            name="corr_open_deal_value",
            field=models.FloatField(
                default=0.85,
                help_text="Значение корреляции для открытия сделки, не менее. Если 0 - не используется.",
                verbose_name="Corr open deal value",
            ),
        ),
        migrations.AlterField(
            model_name="arbitration",
            name="corr_type",
            field=models.CharField(
                choices=[("pearson", "Pearson")],
                default="pearson",
                verbose_name="Corr type",
            ),
        ),
    ]
