# Generated by Django 4.2.3 on 2025-03-10 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0042_arbitration_corr_stop_loss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arbitration",
            old_name="corr_stop_loss",
            new_name="corr_stop_loss_value",
        ),
    ]
