# Generated by Django 4.2.3 on 2025-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbitrations", "0045_arbitration_entry_price_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitration",
            name="entry_price_interval",
            field=models.CharField(
                choices=[("1min", "Minute 1"), ("1D", "Day 1")],
                default="1min",
                help_text="Интервал входных свечей при тестировании стратегии",
                max_length=10,
                verbose_name="Entry price interval",
            ),
        ),
    ]
