# Generated by Django 4.2.3 on 2023-08-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coin",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="coin"
                    ),
                ),
                (
                    "deposit_all_enable",
                    models.BooleanField(verbose_name="depositAllEnable"),
                ),
                (
                    "free",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="free"
                    ),
                ),
                (
                    "freeze",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="freeze"
                    ),
                ),
                (
                    "ipoable",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="ipoable",
                    ),
                ),
                (
                    "ipoing",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="ipoing"
                    ),
                ),
                (
                    "is_legal_money",
                    models.BooleanField(verbose_name="isLegalMoney"),
                ),
                (
                    "locked",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="locked"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "storage",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="storage",
                    ),
                ),
                ("trading", models.BooleanField(verbose_name="trading")),
                (
                    "withdraw_all_enable",
                    models.BooleanField(verbose_name="withdrawAllEnable"),
                ),
                (
                    "withdrawing",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="withdrawing",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Монета",
                "verbose_name_plural": "Монеты",
            },
        ),
    ]
