# Generated by Django 4.2.3 on 2023-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpotBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "coin",
                    models.CharField(max_length=50, unique=True, verbose_name="coin"),
                ),
                (
                    "deposit_all_enable",
                    models.BooleanField(verbose_name="depositAllEnable"),
                ),
                (
                    "free",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="free"
                    ),
                ),
                (
                    "freeze",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="freeze"
                    ),
                ),
                (
                    "ipoable",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="ipoable"
                    ),
                ),
                (
                    "ipoing",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="ipoing"
                    ),
                ),
                ("is_legal_money", models.BooleanField(verbose_name="isLegalMoney")),
                (
                    "locked",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="locked"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "storage",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="storage"
                    ),
                ),
                ("trading", models.BooleanField(verbose_name="trading")),
                (
                    "withdraw_all_enable",
                    models.BooleanField(verbose_name="withdrawAllEnable"),
                ),
                (
                    "withdrawing",
                    models.DecimalField(
                        decimal_places=10, max_digits=12, verbose_name="withdrawing"
                    ),
                ),
            ],
            options={
                "verbose_name": "SPOT баланс",
                "verbose_name_plural": "SPOT баланс",
            },
        ),
        migrations.CreateModel(
            name="TradeFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=50, unique=True, verbose_name="symbol"),
                ),
                (
                    "maker_commission",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="maker_commission"
                    ),
                ),
                (
                    "taker_commission",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="taker_commission"
                    ),
                ),
            ],
            options={
                "verbose_name": "Торговая комиссия",
                "verbose_name_plural": "Торговые комиссии",
            },
        ),
    ]
