# Generated by Django 4.2.3 on 2023-08-25 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotbalance",
            options={
                "verbose_name": "SPOT баланс",
                "verbose_name_plural": "SPOT баланс",
            },
        ),
    ]
