# Generated by Django 4.2.3 on 2023-08-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="symbol"
                    ),
                ),
                (
                    "maker_commission",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="maker_commission",
                    ),
                ),
                (
                    "taker_commission",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="taker_commission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Торговая комиссия",
                "verbose_name_plural": "Торговые комиссии",
            },
        ),
    ]
