# Generated by Django 4.2.3 on 2023-08-24 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_tradefee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotbalance",
            options={
                "verbose_name": "SPOT Balance",
                "verbose_name_plural": "SPOT Balance",
            },
        ),
    ]
