# Generated by Django 4.2.3 on 2023-08-24 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_alter_spotbalance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotbalance",
            options={
                "verbose_name": "SPOT Баланс",
                "verbose_name_plural": "SPOT Баланс",
            },
        ),
    ]
