# Generated by Django 4.2.3 on 2026-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERC20Token",
            fields=[
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Address",
                    ),
                ),
                (
                    "chain_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Chain ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=50, null=True, verbose_name="Symbol"),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Decimals"
                    ),
                ),
                (
                    "total_supply",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Total Supply"
                    ),
                ),
                (
                    "owner",
                    models.CharField(max_length=42, null=True, verbose_name="Owner"),
                ),
                (
                    "version",
                    models.CharField(max_length=50, null=True, verbose_name="Version"),
                ),
                (
                    "domain_separator",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Domain Separator"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "ERC-20 Token",
                "verbose_name_plural": "ERC-20 Tokens",
            },
        ),
    ]
