# Generated by Django 4.2.3 on 2026-05-26 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("liquidity_pools", "0002_erc20token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(max_length=42, verbose_name="Wallet Address"),
                ),
                (
                    "amount_in",
                    models.DecimalField(
                        decimal_places=0, max_digits=78, verbose_name="Amount In"
                    ),
                ),
                (
                    "amount_out_min",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=78,
                        verbose_name="Amount Out Min",
                    ),
                ),
                ("fee", models.PositiveIntegerField(default=500, verbose_name="Fee")),
                (
                    "slippage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=5,
                        verbose_name="Slippage Percent",
                    ),
                ),
                (
                    "deadline_seconds",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Deadline Seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Swap Request",
                "verbose_name_plural": "Swap Requests",
            },
        ),
        migrations.CreateModel(
            name="SwapRequestTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blockchain_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.blockchaintransaction",
                    ),
                ),
                (
                    "swap_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.swaprequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="blockchain_transaction",
            field=models.ManyToManyField(
                related_name="swap_request",
                through="liquidity_pools.SwapRequestTransaction",
                to="liquidity_pools.blockchaintransaction",
                verbose_name="Blockchain Transactions",
            ),
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="token_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_in",
                to="liquidity_pools.erc20token",
                verbose_name="Token In",
            ),
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="token_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_out",
                to="liquidity_pools.erc20token",
                verbose_name="Token Out",
            ),
        ),
    ]
