# Generated by Django 4.2.3 on 2026-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0003_swaprequest_swaprequesttransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="Label"),
                ),
                (
                    "encrypted_private_key",
                    models.JSONField(verbose_name="Encrypted Private Key"),
                ),
                ("chain_id", models.CharField(max_length=32, verbose_name="Chain ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Wallet Address",
                "verbose_name_plural": "Wallet Addresses",
            },
        ),
    ]
