# Generated by Django 4.2.3 on 2026-05-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0004_walletaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaprequest",
            name="wallet_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.walletaddress",
                verbose_name="Wallet Address",
            ),
        ),
    ]
