# Generated by Django 4.2.3 on 2026-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0005_alter_swaprequest_wallet_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaddress",
            name="address",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                unique=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="walletaddress",
            name="encrypted_private_key",
            field=models.JSONField(blank=True, verbose_name="Encrypted Private Key"),
        ),
    ]
