# Generated by Django 4.2.3 on 2026-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0006_alter_walletaddress_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaddress",
            name="address",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Address"
            ),
        ),
    ]
