# Generated by Django 4.2.3 on 2026-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0007_alter_walletaddress_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "chain_id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="Chain ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Chain Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("rpc_urls", models.JSONField(default=list, verbose_name="RPC URLs")),
                (
                    "ws_rpc_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Websocket RPC URLs",
                    ),
                ),
                (
                    "explorer_url",
                    models.URLField(blank=True, verbose_name="Explorer URL"),
                ),
                (
                    "native_token_symbol",
                    models.CharField(
                        default="ETH", max_length=16, verbose_name="Native Token Symbol"
                    ),
                ),
                (
                    "native_token_decimals",
                    models.PositiveSmallIntegerField(
                        default=18, verbose_name="Native Token Decimals"
                    ),
                ),
                (
                    "block_time",
                    models.FloatField(
                        blank=True, help_text="Average block time in seconds", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Chain",
                "verbose_name_plural": "Chains",
            },
        ),
    ]
