# Generated by Django 4.2.3 on 2026-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0008_chain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockchaintransaction",
            options={
                "verbose_name": "Blockchain Transaction",
                "verbose_name_plural": "Blockchain Transactions",
            },
        ),
        migrations.AlterField(
            model_name="walletaddress",
            name="address",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                unique=True,
                verbose_name="Address",
            ),
        ),
    ]
