# Generated by Django 4.2.3 on 2026-05-29 13:48

from django.db import migrations


def code(apps, _):
    Chain = apps.get_model('liquidity_pools', 'Chain')
    Chain.objects.update_or_create(
        chain_id=42161,
        name='Arbitrum One',
        slug='arbitrum',
        rpc_urls=[
            'https://arb1.arbitrum.io/rpc',
            'https://rpc.ankr.com/arbitrum',
        ],
        explorer_url='https://arbiscan.io/',
        native_token_symbol='ETH',
        native_token_decimals=18,
        block_time=0.25,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0009_alter_blockchaintransaction_options_and_more"),
    ]

    operations = [
        migrations.RunPython(code, reverse_code=migrations.RunPython.noop),
    ]
