# Generated by Django 4.2.3 on 2026-05-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0010_auto_20260529_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaddress",
            name="chain_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.chain",
                verbose_name="Chain ID",
            ),
        ),
    ]
