# Generated by Django 4.2.3 on 2026-05-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0012_alter_blockchaintransaction_chain_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erc20token",
            name="chain_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.chain",
                verbose_name="Chain ID",
            ),
        ),
    ]
