# Generated by Django 4.2.3 on 2026-05-29 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0013_alter_erc20token_chain_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockchaintransaction",
            old_name="chain_id",
            new_name="chain",
        ),
        migrations.RenameField(
            model_name="chain",
            old_name="chain_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="erc20token",
            old_name="chain_id",
            new_name="chain",
        ),
        migrations.RenameField(
            model_name="walletaddress",
            old_name="chain_id",
            new_name="chain",
        ),
    ]
