# Generated by Django 4.2.3 on 2026-05-29 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquidity_pools",
            "0014_rename_chain_id_blockchaintransaction_chain_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swaprequest",
            name="amount_out_min",
        ),
    ]
