# Generated by Django 4.2.3 on 2026-05-31 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "liquidity_pools",
            "0014_rename_chain_id_blockchaintransaction_chain_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityMintRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount0_desired",
                    models.DecimalField(
                        decimal_places=0, max_digits=78, verbose_name="Amount0 Desired"
                    ),
                ),
                (
                    "amount1_desired",
                    models.DecimalField(
                        decimal_places=0, max_digits=78, verbose_name="Amount1 Desired"
                    ),
                ),
                (
                    "range_upper_price",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Price in Token1",
                        max_digits=78,
                        verbose_name="Range Upper Limit",
                    ),
                ),
                (
                    "range_lower_print",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Price in Token1",
                        max_digits=78,
                        verbose_name="Range Lower Limit",
                    ),
                ),
                (
                    "amount0_min",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=78,
                        verbose_name="Amount0 Min",
                    ),
                ),
                (
                    "amount1_min",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=78,
                        verbose_name="Amount1 Min",
                    ),
                ),
                (
                    "slippage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=5,
                        verbose_name="Slippage Percent",
                    ),
                ),
                (
                    "deadline_seconds",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Deadline Seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Liquidity Mint Request",
                "verbose_name_plural": "Liquidity Mint Requests",
            },
        ),
        migrations.CreateModel(
            name="LiquidityRemovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_token_id",
                    models.PositiveBigIntegerField(verbose_name="Pool Token ID"),
                ),
                (
                    "removal_percentage",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Removal Percentage"
                    ),
                ),
                (
                    "deadline_seconds",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Deadline Seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Liquidity Removal Request",
                "verbose_name_plural": "Liquidity Removal Requests",
            },
        ),
        migrations.RemoveField(
            model_name="swaprequest",
            name="amount_out_min",
        ),
        migrations.CreateModel(
            name="LiquidityRemovalRequestTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blockchain_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.blockchaintransaction",
                    ),
                ),
                (
                    "liquidity_removal_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquidityremovalrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="liquidityremovalrequest",
            name="blockchain_transaction",
            field=models.ManyToManyField(
                related_name="liquidity_removal_request",
                through="liquidity_pools.LiquidityRemovalRequestTransaction",
                to="liquidity_pools.blockchaintransaction",
                verbose_name="Blockchain Transactions",
            ),
        ),
        migrations.AddField(
            model_name="liquidityremovalrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquidityremovalrequest",
            name="wallet_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.walletaddress",
                verbose_name="Wallet Address",
            ),
        ),
        migrations.CreateModel(
            name="LiquidityPool",
            fields=[
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Pool Address",
                    ),
                ),
                (
                    "fee",
                    models.PositiveIntegerField(
                        help_text="100, 500, 3000, 10000", null=True, verbose_name="Fee"
                    ),
                ),
                (
                    "tick_spacing",
                    models.PositiveIntegerField(null=True, verbose_name="Tick Spacing"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.chain",
                        verbose_name="Chain",
                    ),
                ),
                (
                    "token0",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token0_pools",
                        to="liquidity_pools.erc20token",
                        verbose_name="Token0",
                    ),
                ),
                (
                    "token1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token1_pools",
                        to="liquidity_pools.erc20token",
                        verbose_name="Token1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidity Pool",
                "verbose_name_plural": "Liquidity Pools",
            },
        ),
        migrations.CreateModel(
            name="LiquidityMintRequestTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blockchain_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.blockchaintransaction",
                    ),
                ),
                (
                    "liquidity_mint_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquiditymintrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="blockchain_transaction",
            field=models.ManyToManyField(
                related_name="liquidity_mint_request",
                through="liquidity_pools.LiquidityMintRequestTransaction",
                to="liquidity_pools.blockchaintransaction",
                verbose_name="Blockchain Transactions",
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="liquidity_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.liquiditypool",
                verbose_name="Liquidity Pool",
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="wallet_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.walletaddress",
                verbose_name="Wallet Address",
            ),
        ),
    ]
