# Generated by Django 4.2.3 on 2026-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquidity_pools",
            "0015_liquiditymintrequest_liquidityremovalrequest_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquiditymintrequest",
            name="range_lower_print",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Price in Token1",
                max_digits=78,
                verbose_name="Range Lower Price",
            ),
        ),
        migrations.AlterField(
            model_name="liquiditymintrequest",
            name="range_upper_price",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Price in Token1",
                max_digits=78,
                verbose_name="Range Upper Price",
            ),
        ),
    ]
