# Generated by Django 4.2.3 on 2026-05-29 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("liquidity_pools", "0015_remove_swaprequest_amount_out_min"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityRemovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_token_id",
                    models.PositiveBigIntegerField(verbose_name="Pool Token ID"),
                ),
                (
                    "removal_percentage",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Removal Percentage"
                    ),
                ),
                (
                    "deadline_seconds",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Deadline Seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Liquidity Removal Request",
                "verbose_name_plural": "Liquidity Removal Requests",
            },
        ),
        migrations.CreateModel(
            name="LiquidityRemovalRequestTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blockchain_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.blockchaintransaction",
                    ),
                ),
                (
                    "liquidity_removal_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquidityremovalrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="liquidityremovalrequest",
            name="blockchain_transaction",
            field=models.ManyToManyField(
                related_name="liquidity_removal_request",
                through="liquidity_pools.LiquidityRemovalRequestTransaction",
                to="liquidity_pools.blockchaintransaction",
                verbose_name="Blockchain Transactions",
            ),
        ),
        migrations.AddField(
            model_name="liquidityremovalrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquidityremovalrequest",
            name="wallet_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.walletaddress",
                verbose_name="Wallet Address",
            ),
        ),
    ]
