# Generated by Django 4.2.3 on 2026-05-31 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquidity_pools",
            "0016_alter_liquiditymintrequest_range_lower_print_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="liquiditymintrequest",
            old_name="range_lower_print",
            new_name="range_lower_price",
        ),
    ]
