# Generated by Django 4.2.3 on 2026-05-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("liquidity_pools", "0016_liquidityremovalrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityMintRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.PositiveIntegerField(default=500, verbose_name="Fee")),
                (
                    "pool_address",
                    models.CharField(max_length=42, verbose_name="Pool Address"),
                ),
                (
                    "amount0_desired",
                    models.PositiveBigIntegerField(verbose_name="Amount0 Desired"),
                ),
                (
                    "amount1_desired",
                    models.PositiveBigIntegerField(verbose_name="Amount1 Desired"),
                ),
                (
                    "tick_width",
                    models.PositiveBigIntegerField(verbose_name="Tick Width"),
                ),
                ("range_up", models.PositiveBigIntegerField(verbose_name="Range Up")),
                (
                    "range_down",
                    models.PositiveBigIntegerField(verbose_name="Range Down"),
                ),
                (
                    "amount0_min",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Amount0 Min"
                    ),
                ),
                (
                    "amount1_min",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Amount1 Min"
                    ),
                ),
                (
                    "slippage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=5,
                        verbose_name="Slippage Percent",
                    ),
                ),
                (
                    "deadline_seconds",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Deadline Seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Liquidity Mint Request",
                "verbose_name_plural": "Liquidity Mint Requests",
            },
        ),
        migrations.CreateModel(
            name="LiquidityMintRequestTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blockchain_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.blockchaintransaction",
                    ),
                ),
                (
                    "liquidity_mint_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquiditymintrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="blockchain_transaction",
            field=models.ManyToManyField(
                related_name="liquidity_mint_request",
                through="liquidity_pools.LiquidityMintRequestTransaction",
                to="liquidity_pools.blockchaintransaction",
                verbose_name="Blockchain Transactions",
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="token1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token1",
                to="liquidity_pools.erc20token",
                verbose_name="Token 1",
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="token2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token2",
                to="liquidity_pools.erc20token",
                verbose_name="Token 2",
            ),
        ),
        migrations.AddField(
            model_name="liquiditymintrequest",
            name="wallet_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="liquidity_pools.walletaddress",
                verbose_name="Wallet Address",
            ),
        ),
    ]
