# Generated by Django 4.2.3 on 2026-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquidity_pools",
            "0017_liquiditymintrequest_liquiditymintrequesttransaction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liquiditymintrequest",
            name="tick_width",
        ),
        migrations.AlterField(
            model_name="liquiditymintrequest",
            name="range_lower_limit",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Price in USD",
                max_digits=78,
                verbose_name="Range Lower Limit",
            ),
        ),
        migrations.AlterField(
            model_name="liquiditymintrequest",
            name="range_upper_limit",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Price in USD",
                max_digits=78,
                verbose_name="Range Upper Limit",
            ),
        ),
    ]
