# Generated by Django 4.2.3 on 2026-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquidity_pools",
            "0017_rename_range_lower_print_liquiditymintrequest_range_lower_price",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="tx_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("swap", "Swap"),
                    ("mint", "Mint"),
                    ("burn", "Burn"),
                    ("collect", "Collect"),
                    ("approve", "Approve"),
                    ("decrease_liquidity", "Decrease Liquidity"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
                verbose_name="Transaction Type",
            ),
        ),
    ]
