# Generated by Django 4.2.3 on 2026-05-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0018_remove_liquiditymintrequest_tick_width_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityPool",
            fields=[
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Pool Address",
                    ),
                ),
                (
                    "fee",
                    models.PositiveIntegerField(
                        help_text="100, 500, 3000, 10000", verbose_name="Fee"
                    ),
                ),
                (
                    "tick_spacing",
                    models.PositiveIntegerField(verbose_name="Tick Spacing"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.chain",
                        verbose_name="Chain",
                    ),
                ),
                (
                    "token0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token0_pools",
                        to="liquidity_pools.erc20token",
                        verbose_name="Token0",
                    ),
                ),
                (
                    "token1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token1_pools",
                        to="liquidity_pools.erc20token",
                        verbose_name="Token1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidity Pool",
                "verbose_name_plural": "Liquidity Pools",
            },
        ),
    ]
