# Generated by Django 4.2.3 on 2026-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0018_alter_blockchaintransaction_tx_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquiditymintrequest",
            name="slippage_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Не использую. Но можно прикрутить так: выбирать меньшее значение из amount0_desired/amount1_desired, применяешь значение из этого поля и заполняешь соответствующее поле amount0_min/amount1_min. Во втором поле amount_min ставим 0. Получается страховка от ситуации, когда цена сильно уехала после отпарвки транзакции. Не уверен что это нужно сейчас.",
                max_digits=5,
                verbose_name="Slippage Percent",
            ),
        ),
    ]
