# Generated by Django 4.2.3 on 2026-05-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0019_liquiditypool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquiditypool",
            name="fee",
            field=models.PositiveIntegerField(
                help_text="100, 500, 3000, 10000", null=True, verbose_name="Fee"
            ),
        ),
        migrations.AlterField(
            model_name="liquiditypool",
            name="tick_spacing",
            field=models.PositiveIntegerField(null=True, verbose_name="Tick Spacing"),
        ),
        migrations.AlterField(
            model_name="liquiditypool",
            name="token0",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token0_pools",
                to="liquidity_pools.erc20token",
                verbose_name="Token0",
            ),
        ),
        migrations.AlterField(
            model_name="liquiditypool",
            name="token1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token1_pools",
                to="liquidity_pools.erc20token",
                verbose_name="Token1",
            ),
        ),
    ]
