# Generated by Django 4.2.3 on 2026-06-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0019_alter_liquiditymintrequest_slippage_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityPoolTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_number",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Block Number"
                    ),
                ),
                ("tick", models.IntegerField(verbose_name="Tick")),
                (
                    "liquidity",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Liquidity"
                    ),
                ),
                (
                    "block_timestamp",
                    models.DateTimeField(verbose_name="Block Timestamp"),
                ),
                (
                    "liquidity_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquiditypool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidity Pool Tick",
                "verbose_name_plural": "Liquidity Pool Ticks",
                "indexes": [
                    models.Index(
                        fields=["liquidity_pool", "block_timestamp"],
                        name="liquidity_p_liquidi_08c01b_idx",
                    )
                ],
            },
        ),
    ]
