# Generated by Django 4.2.3 on 2026-06-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0019_alter_liquiditymintrequest_slippage_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoolTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_number",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Block Number"
                    ),
                ),
                ("tick", models.IntegerField(verbose_name="Tick")),
                (
                    "liquidity",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Liquidity"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquiditypool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pool Tick",
                "verbose_name_plural": "Pool Ticks",
                "indexes": [
                    models.Index(
                        fields=["pool", "created_at"],
                        name="liquidity_p_pool_id_f58fbe_idx",
                    )
                ],
            },
        ),
    ]
