# Generated by Django 4.2.3 on 2026-06-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0020_liquiditypooltick"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("5m", "Minute 5"),
                            ("15m", "Minute 15"),
                            ("30m", "Minute 30"),
                            ("1h", "Hour 1"),
                            ("2h", "Hour 2"),
                            ("4h", "Hour 4"),
                            ("6h", "Hour 6"),
                            ("8h", "Hour 8"),
                            ("12h", "Hour 12"),
                            ("1D", "Day 1"),
                            ("3D", "Day 3"),
                            ("1W", "Week 1"),
                            ("1M", "Month 1"),
                            ("1A", "Year 1"),
                        ],
                        default="1D",
                        max_length=50,
                        verbose_name="Interval",
                    ),
                ),
                (
                    "std_window_size",
                    models.PositiveIntegerField(default=7, verbose_name="Window Size"),
                ),
                (
                    "std_source",
                    models.CharField(
                        choices=[
                            ("close_to_close", "Realized volatility"),
                            ("parkinson", "Parkinson volatility"),
                        ],
                        default="close_to_close",
                        max_length=50,
                        verbose_name="Source",
                    ),
                ),
                (
                    "z_score_upper",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="Z-Score Upper"
                    ),
                ),
                (
                    "z_score_lower",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="Z-Score Upper"
                    ),
                ),
                (
                    "time_horizon",
                    models.CharField(
                        choices=[
                            ("5m", "Minute 5"),
                            ("15m", "Minute 15"),
                            ("30m", "Minute 30"),
                            ("1h", "Hour 1"),
                            ("2h", "Hour 2"),
                            ("4h", "Hour 4"),
                            ("6h", "Hour 6"),
                            ("8h", "Hour 8"),
                            ("12h", "Hour 12"),
                            ("1D", "Day 1"),
                            ("3D", "Day 3"),
                            ("1W", "Week 1"),
                            ("1M", "Month 1"),
                            ("1A", "Year 1"),
                        ],
                        default="1D",
                        max_length=50,
                        verbose_name="Time Horizon",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "liquidity_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquiditypool",
                        verbose_name="Liquidity Pool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
            },
        ),
    ]
