# Generated by Django 4.2.3 on 2026-06-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0021_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="closing_trade_condition",
            field=models.CharField(
                choices=[
                    ("better_order", "Better, upper limit first"),
                    ("worse_order", "Worse, lower limit first"),
                ],
                default="worse_order",
                help_text="Если свеча пересекает обе границы, какое пересечение считать первым7",
                max_length=50,
                verbose_name="Closing Trade Condition",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="entering_trade_condition",
            field=models.CharField(
                choices=[("open_price", "Candle open price")],
                default="open_price",
                max_length=50,
                verbose_name="Entering Trade Condition",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="z_score_lower",
            field=models.DecimalField(
                decimal_places=1, max_digits=2, verbose_name="Z-Score Lower"
            ),
        ),
    ]
