# Generated by Django 4.2.3 on 2026-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0022_strategy_closing_trade_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="maximum_range_width",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Maximum Range Width"
            ),
        ),
    ]
