# Generated by Django 4.2.3 on 2026-06-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0023_strategy_maximum_range_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Opened at"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed at"
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=18, max_digits=30, verbose_name="Entry Price"
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=30,
                        null=True,
                        verbose_name="Exit Price",
                    ),
                ),
                (
                    "lower_price",
                    models.DecimalField(
                        decimal_places=18, max_digits=30, verbose_name="Lower Price"
                    ),
                ),
                (
                    "upper_price",
                    models.DecimalField(
                        decimal_places=18, max_digits=30, verbose_name="Upper Price"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed_by_range", "Closed by range"),
                            ("closed_for_rebalancing", "Closed for rebalancing"),
                            ("closed_manual", "Closed manual"),
                        ],
                        default="open",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "liquidity_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.liquiditypool",
                        verbose_name="Liquidity Pool",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.strategy",
                        verbose_name="Strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Position",
                "verbose_name_plural": "Strategy Positions",
            },
        ),
    ]
