# Generated by Django 4.2.3 on 2026-06-08 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0024_strategyposition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategyposition",
            name="liquidity_pool",
        ),
    ]
