# Generated by Django 4.2.3 on 2026-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0025_remove_strategyposition_liquidity_pool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="closing_trade_condition",
        ),
        migrations.AddField(
            model_name="strategy",
            name="intrabar_price_path",
            field=models.CharField(
                choices=[("ohlc", "Better, high first"), ("olhc", "Worse, low first")],
                default="ohlc",
                max_length=50,
                verbose_name="Intrabar Price Path",
            ),
        ),
    ]
