# Generated by Django 4.2.3 on 2026-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0026_remove_strategy_closing_trade_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="is_recalculated_by_chart_update",
            field=models.BooleanField(
                default=False, verbose_name="Recalculated by Chart Update"
            ),
        ),
    ]
