# Generated by Django 4.2.3 on 2026-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0027_strategy_is_recalculated_by_chart_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="intrabar_price_path",
        ),
        migrations.AddField(
            model_name="strategy",
            name="block_timestamp_end",
            field=models.DateTimeField(
                blank=True,
                help_text="If null, backtest using all tick data.",
                null=True,
                verbose_name="Block Timestamp End",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="block_timestamp_start",
            field=models.DateTimeField(
                blank=True,
                help_text="If null, backtest using all tick data.",
                null=True,
                verbose_name="Block Timestamp Start",
            ),
        ),
    ]
