# Generated by Django 4.2.3 on 2026-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0028_remove_strategy_intrabar_price_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="interval",
            field=models.CharField(
                choices=[
                    ("5min", "Minute 5"),
                    ("15min", "Minute 15"),
                    ("30min", "Minute 30"),
                    ("1h", "Hour 1"),
                    ("2h", "Hour 2"),
                    ("4h", "Hour 4"),
                    ("6h", "Hour 6"),
                    ("8h", "Hour 8"),
                    ("12H", "Hour 12"),
                    ("1D", "Day 1"),
                    ("3D", "Day 3"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                default="1D",
                max_length=50,
                verbose_name="Interval",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="time_horizon",
            field=models.CharField(
                choices=[
                    ("5min", "Minute 5"),
                    ("15min", "Minute 15"),
                    ("30min", "Minute 30"),
                    ("1h", "Hour 1"),
                    ("2h", "Hour 2"),
                    ("4h", "Hour 4"),
                    ("6h", "Hour 6"),
                    ("8h", "Hour 8"),
                    ("12H", "Hour 12"),
                    ("1D", "Day 1"),
                    ("3D", "Day 3"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                default="1D",
                max_length=50,
                verbose_name="Time Horizon",
            ),
        ),
    ]
