# Generated by Django 4.2.3 on 2026-06-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("liquidity_pools", "0030_alter_strategy_interval_alter_strategy_time_horizon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="entering_trade_condition",
        ),
        migrations.AlterField(
            model_name="strategy",
            name="interval",
            field=models.CharField(
                choices=[
                    ("1min", "Minute 1"),
                    ("3min", "Minute 3"),
                    ("5min", "Minute 5"),
                    ("15min", "Minute 15"),
                    ("30min", "Minute 30"),
                    ("1H", "Hour 1"),
                    ("2H", "Hour 2"),
                    ("4H", "Hour 4"),
                    ("6H", "Hour 6"),
                    ("8H", "Hour 8"),
                    ("12H", "Hour 12"),
                    ("1D", "Day 1"),
                    ("3D", "Day 3"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                default="1D",
                max_length=50,
                verbose_name="Interval",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="time_horizon",
            field=models.CharField(
                choices=[
                    ("1min", "Minute 1"),
                    ("3min", "Minute 3"),
                    ("5min", "Minute 5"),
                    ("15min", "Minute 15"),
                    ("30min", "Minute 30"),
                    ("1H", "Hour 1"),
                    ("2H", "Hour 2"),
                    ("4H", "Hour 4"),
                    ("6H", "Hour 6"),
                    ("8H", "Hour 8"),
                    ("12H", "Hour 12"),
                    ("1D", "Day 1"),
                    ("3D", "Day 3"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                default="1D",
                max_length=50,
                verbose_name="Time Horizon",
            ),
        ),
        migrations.CreateModel(
            name="StrategyCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tick_data_complete",
                    models.BooleanField(
                        default=False,
                        help_text="For the current windows_size and interval",
                        verbose_name="Tick Data is Complete",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidity_pools.strategy",
                        verbose_name="Strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Check",
                "verbose_name_plural": "Strategy Checks",
            },
        ),
    ]
