# Generated by Django 4.2.3 on 2024-09-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market_data", "0002_auto_20240819_0114"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Codename"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1m", "Minute 1"),
                            ("3m", "Minute 3"),
                            ("5m", "Minute 5"),
                            ("15m", "Minute 15"),
                            ("30m", "Minute 30"),
                            ("1h", "Hour 1"),
                            ("2h", "Hour 2"),
                            ("4h", "Hour 4"),
                            ("6h", "Hour 6"),
                            ("8h", "Hour 8"),
                            ("12h", "Hour 12"),
                            ("1d", "Day 1"),
                            ("3d", "Day 3"),
                            ("1w", "Week 1"),
                            ("1M", "Month 1"),
                        ],
                        max_length=5,
                        verbose_name="Interval",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Stopped"), (1, "Active"), (2, "Testing")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.exchangeinfo",
                        verbose_name="Symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
            },
        ),
    ]
