# Generated by Django 4.2.3 on 2024-05-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("codename", models.CharField(max_length=100, verbose_name="Codename")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Stopped"), (1, "Active"), (2, "Testing")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
            },
        ),
        migrations.CreateModel(
            name="AveragePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_time",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="serverTime"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("codename", models.CharField(max_length=100, verbose_name="Codename")),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="strategies.strategy",
                        verbose_name="Strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "AveragePrice",
                "verbose_name_plural": "AveragePrice",
            },
        ),
    ]
