# Generated by Django 4.2.3 on 2024-05-12 20:10

from django.db import migrations

NAME = 'Default'
CODENAME = 'default'


def code(apps, *_):
    Strategy = apps.get_model('strategies.Strategy')
    Strategy.objects.create(
        name=NAME,
        codename=CODENAME,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code, atomic=True),
    ]
