# Generated by Django 4.2.3 on 2024-05-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyCommonVars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=100, verbose_name="Codename")),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                ("group", models.CharField(max_length=255, verbose_name="Group")),
            ],
            options={
                "verbose_name": "Strategy Common Vars",
                "verbose_name_plural": "Strategy Common Vars",
            },
        ),
    ]
