# Generated by Django 4.2.3 on 2024-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0002_remove_strategy_moving_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AddField(
            model_name="strategy",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start time"
            ),
        ),
    ]
