# Generated by Django 4.2.3 on 2024-09-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0003_strategyresult"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="strategyresult",
            index=models.Index(
                fields=["strategy", "kline"], name="strategies__strateg_46b97a_idx"
            ),
        ),
    ]
