# Generated by Django 4.2.3 on 2024-05-12 22:22

from django.db import migrations

STRATEGY_CODENAME = 'default'

NAME = 'Свечи для расчета'
CODENAME = 'calculate_candles'
VALUE = 'realtime'
DESCRIPTION = '''В реальном времени: 'realtime',
По последней закрытой свече: 'last_candle',
'''



def code(apps, *_):
    Strategy = apps.get_model('strategies.Strategy')
    strategy = Strategy.objects.get(
        codename=STRATEGY_CODENAME,
    )

    AveragePrice = apps.get_model('strategies.AveragePrice')
    AveragePrice.objects.create(
        strategy=strategy,
        name=NAME,
        codename=CODENAME,
        value=VALUE,
        description=DESCRIPTION,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0003_auto_20240512_2321"),
    ]

    operations = [
        migrations.RunPython(code, atomic=True),
    ]
