# Generated by Django 4.2.3 on 2024-05-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0004_auto_20240513_0122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averageprice",
            name="codename",
            field=models.CharField(max_length=100, verbose_name="Codename"),
        ),
        migrations.AlterField(
            model_name="averageprice",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="averageprice",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="strategies.strategy",
                verbose_name="Strategy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="averageprice",
            unique_together={("strategy", "codename")},
        ),
    ]
