# Generated by Django 4.2.3 on 2024-11-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0004_alter_strategy_codename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="codename",
            field=models.CharField(
                choices=[("strategy_1", "Strategy_1")],
                max_length=255,
                unique=True,
                verbose_name="Codename",
            ),
        ),
    ]
