# Generated by Django 4.2.3 on 2024-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0005_alter_strategy_codename"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyresult",
            name="state",
            field=models.TextField(
                choices=[("open", "Open"), ("profit", "Profit"), ("loss", "Loss")],
                default="open",
                verbose_name="State",
            ),
        ),
    ]
