# Generated by Django 4.2.3 on 2024-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0006_strategyresult_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategyresult",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("profit", "Profit"),
                    ("loss", "Loss"),
                    ("unknown", "Unknown"),
                ],
                verbose_name="State",
            ),
        ),
    ]
