# Generated by Django 4.2.3 on 2024-11-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0007_alter_strategyresult_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyresult",
            name="deal_time",
            field=models.DateTimeField(default=None, verbose_name="Deal time"),
            preserve_default=False,
        ),
    ]
