# Generated by Django 4.2.3 on 2024-11-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0008_strategyresult_deal_time"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="strategyresult",
            name="strategies__strateg_46b97a_idx",
        ),
        migrations.RemoveField(
            model_name="strategyresult",
            name="kline",
        ),
        migrations.AddIndex(
            model_name="strategyresult",
            index=models.Index(
                fields=["strategy", "deal_time"], name="strategies__strateg_705dde_idx"
            ),
        ),
    ]
