# Generated by Django 4.2.3 on 2024-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0010_strategy_direction_deals"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="entry_price_order",
            field=models.CharField(
                choices=[
                    ("MAXMIN", "MaxMin"),
                    ("MINMAX", "MinMax"),
                    ("RANDOM", "Random"),
                ],
                default="MAXMIN",
                help_text="В каком порядке подавать цены свечи при тестировании стратегии.",
                max_length=50,
                verbose_name="Entry price order",
            ),
        ),
    ]
