# Generated by Django 4.2.3 on 2024-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0011_strategy_entry_price_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="direction_deals",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("only_sell", "Only sell"),
                    ("only_buy", "Only buy"),
                ],
                default="default",
                help_text="Если default то тренд определяется самой стратегией",
                max_length=50,
                verbose_name="Direction deals",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="entry_price_order",
            field=models.CharField(
                choices=[
                    ("MAXMIN", "MaxMin"),
                    ("MINMAX", "MinMax"),
                    ("RANDOM", "Random"),
                ],
                default="MAXMIN",
                help_text="В каком порядке подавать цены свечи при тестировании стратегии",
                max_length=50,
                verbose_name="Entry price order",
            ),
        ),
    ]
