# Generated by Django 4.2.3 on 2024-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0015_alter_strategy_codename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="entry_price_order",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open price"),
                    ("CLOSE", "Close price"),
                    ("HIGH", "High price"),
                    ("LOW", "Low price"),
                    ("MAXMIN", "MaxMin"),
                    ("MINMAX", "MinMax"),
                ],
                default="MAXMIN",
                help_text="В каком порядке подавать цены свечи при тестировании стратегии",
                max_length=50,
                verbose_name="Entry price order",
            ),
        ),
    ]
