# Generated by Django 4.2.3 on 2025-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0016_alter_strategy_entry_price_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="base_interval",
            field=models.CharField(
                choices=[
                    ("1T", "Minute 1"),
                    ("1H", "Hour 1"),
                    ("1D", "Day 1"),
                    ("1W", "Week 1"),
                    ("1M", "Month 1"),
                    ("1A", "Year 1"),
                ],
                default="1T",
                max_length=10,
                verbose_name="Base interval",
            ),
        ),
    ]
